apiVersion: v1
kind: PersistentVolume
metadata:
  name: exam-richard-pv

spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/uploads
    type: DirectoryOrCreate