apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exam-richard-pvc
  namespace: exam-richard
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi